<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:str="http://www.sivi.org/Verzuimmanagement/RapportageArbodienstVerzekeraar/2022" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.sivi.org/Verzuimmanagement/RapportageArbodienstVerzekeraar/2022" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2022.0">
	<xsd:element name="RapportageArbodienstVerzekeraar">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="BrAlg">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="BrCd">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:maxLength value="5"/>
										<xsd:enumeration value="00703"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="VnrBrCd">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:maxLength value="5"/>
										<xsd:enumeration value="00002"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="AandatBr" type="xsd:date"/>
							<xsd:element name="AantijdBr" type="xsd:time"/>
							<xsd:element name="IdInzndr" type="str:IdentificatieInzender"/>
							<xsd:element name="GebrSwPakket" type="str:Tekst35"/>
							<xsd:element name="IdOntvngr" type="str:IdentificatieOntvanger"/>
							<xsd:element name="Berrefnr" type="str:Berichtreferentienummer"/>
							<xsd:element name="TestJN" type="str:LogischeEenheid"/>
							<xsd:element name="OntvngstbevJN" type="str:LogischeEenheid"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="VrzkrVolmacht" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="HndlsnmOrg" type="str:HandelsnaamOrganisatie"/>
							<xsd:element name="IdVrzkrVolmachtCd" type="str:IdentificatieVerzekeraarCode"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Arbdnst" minOccurs="0">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="HndlsnmOrg" type="str:HandelsnaamOrganisatie"/>
							<xsd:element name="ArbdnstCd" type="str:CodeArbodienst" minOccurs="0"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Verslagperiode" maxOccurs="999">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="Ingdat" type="xsd:date"/>
							<xsd:element name="Enddat" type="xsd:date"/>
							<xsd:element name="Rapportage">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="AantalKlanten" type="str:Aantal7"/>
										<xsd:element name="AantalMeldingen" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalVerzuimmeldingen" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalVerzuimdagen" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="Verzuimpercentage" type="str:Percentage" minOccurs="0"/>
										<xsd:element name="Verzuimfrequentie" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalDeelherstelmeldingen" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="PercentageDeelherstelmeldingen" type="str:Percentage" minOccurs="0"/>
										<xsd:element name="AantalHerstelmeldingen" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="PercentageHerstelmeldingen" type="str:Percentage" minOccurs="0"/>
										<xsd:element name="AantalMeldingenRegres" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="GemiddeldeVerzuimduur" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="ZiekteverzuimpercentageKort" type="str:Percentage" minOccurs="0"/>
										<xsd:element name="ZiekteverzuimpercentageMiddellang" type="str:Percentage" minOccurs="0"/>
										<xsd:element name="ZiekteverzuimpercentageLang" type="str:Percentage" minOccurs="0"/>
										<xsd:element name="ZiekteverzuimpercentageExtraLang" type="str:Percentage" minOccurs="0"/>
										<xsd:element name="AantalMeldingenVerzuimKort" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalMeldingenVerzuimMiddellang" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalMeldingenVerzuimLang" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalMeldingenVerzuimExtraLang" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalZiekdagenKort" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalZiekdagenMiddellang" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalZiekdagenLang" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalZiekdagenExtraLang" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalProbleemanalysesOpgesteld" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="PercentageProbleemanalysesOpTijd" type="str:Percentage" minOccurs="0"/>
										<xsd:element name="AantalPlannenVanAanpakOpgesteld" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="PercentagePlannenVanAanpakOpTijd" type="str:Percentage" minOccurs="0"/>
										<xsd:element name="AantalTweeenveertigWeeksmeldingenGedaan" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="PercentageTweeenveertigWeeksmeldingenOpTijd" type="str:Percentage" minOccurs="0"/>
										<xsd:element name="AantalEindejaarsevaluatiesGedaan" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="PercentageEindejaarsevaluatiesOpTijd" type="str:Percentage" minOccurs="0"/>
										<xsd:element name="AantalReintegratieverslagenOpgesteld" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="PercentageReintegratieverslagenOpTijd" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalPoortwachtersancties" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalGeadviseerdeInterventies" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalGeaccordeerdeInterventies" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalInterventiesMetBijdrageVerzekeraar" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="KostenInterventiesVootVerzekeraar" type="str:Bedrag92" minOccurs="0"/>
										<xsd:element name="AantalTweedeSpoor" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalPsychischeInterventies" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalFysiekeInterventies" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalMultidisciplinaireInterventies" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalWachtlijstbemiddelingen" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalOverigeInterventies" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="Werkgevertevredenheid" type="str:Aantal3" minOccurs="0"/>
										<xsd:element name="AantalGemeldeKlachten" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalTerechteKlachten" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="PercentageTerechteKlachten" type="str:Percentage" minOccurs="0"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="Aantal3">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:totalDigits value="3"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Aantal7">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:totalDigits value="7"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Bedrag92">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="9"/>
			<xsd:fractionDigits value="2"/>
			<xsd:pattern value="[\-+]?[0-9]{1,7}[.][0-9]{2}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Berichtreferentienummer">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="512"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CodeArbodienst">
		<xsd:restriction base="xsd:string">
			<xsd:length value="3"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="HandelsnaamOrganisatie">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="IdentificatieInzender">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="40"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="IdentificatieOntvanger">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="40"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="IdentificatieVerzekeraarCode">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="LogischeEenheid">
		<xsd:restriction base="xsd:string">
			<xsd:length value="1"/>
			<xsd:pattern value="\D*"/>
			<xsd:enumeration value="J"/>
			<xsd:enumeration value="N"/>
			<xsd:enumeration value="O"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Percentage">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="6"/>
			<xsd:fractionDigits value="2"/>
			<xsd:minInclusive value="0"/>
			<xsd:pattern value="[0-9]{1,4}[.][0-9]{2}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Tekst35">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="35"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>
