<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:str="http://www.sivi.org/Verzuimmanagement/UitwisselenKoppelcontractgegevens/2026" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.sivi.org/Verzuimmanagement/UitwisselenKoppelcontractgegevens/2026" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2026.0">
	<xsd:element name="UitwisselenKoppelcontractgegevens">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="BrAlg">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="BrCd">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:maxLength value="5"/>
										<xsd:enumeration value="00700"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="VnrBrCd">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:maxLength value="5"/>
										<xsd:enumeration value="00006"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="FunctieBrCd">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:length value="2"/>
										<xsd:enumeration value="01"/>
										<xsd:enumeration value="02"/>
										<xsd:enumeration value="03"/>
										<xsd:enumeration value="04"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="AandatBr" type="xsd:date"/>
							<xsd:element name="AantijdBr" type="xsd:time"/>
							<xsd:element name="IdInzndr" type="str:IdentificatieInzender"/>
							<xsd:element name="GebrSwPakket" type="str:Tekst35"/>
							<xsd:element name="IdOntvngr" type="str:IdentificatieOntvanger"/>
							<xsd:element name="Berrefnr" type="str:Berichtreferentienummer"/>
							<xsd:element name="BerrefnrIngzndnBer" type="str:Berichtreferentienummer" minOccurs="0"/>
							<xsd:element name="TestJN">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:length value="1"/>
										<xsd:pattern value="\D*"/>
										<xsd:enumeration value="J"/>
										<xsd:enumeration value="N"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="OntvngstbevJN">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:length value="1"/>
										<xsd:pattern value="\D*"/>
										<xsd:enumeration value="J"/>
										<xsd:enumeration value="N"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
							<xsd:element name="CntrctGegGewenstJN">
								<xsd:simpleType>
									<xsd:restriction base="xsd:string">
										<xsd:length value="1"/>
										<xsd:pattern value="\D*"/>
										<xsd:enumeration value="J"/>
										<xsd:enumeration value="N"/>
									</xsd:restriction>
								</xsd:simpleType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="VrzkrVolmacht">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="HndlsnmOrg" type="str:HandelsnaamOrganisatie"/>
							<xsd:element name="IdVrzkrVolmachtCd" type="str:IdentificatieVerzekeraarCode"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Arbdnst">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="HndlsnmOrg" type="str:HandelsnaamOrganisatie" minOccurs="0"/>
							<xsd:element name="ArbdnstCd" type="str:CodeArbodienst"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="Wrkgvr" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="VrwrkCd" type="str:Verwerkingscode"/>
							<xsd:element name="HndlsnmOrg" type="str:HandelsnaamOrganisatie"/>
							<xsd:element name="InschrijvingsnrKvK" type="str:Nummer" minOccurs="0"/>
							<xsd:element name="VestigingsnrHandelsregister" type="str:VestigingsnummerHandelsregister" minOccurs="0"/>
							<xsd:element name="IdWrkgvrArbdnst" type="str:IdentificatieWerkgever" minOccurs="0"/>
							<xsd:element name="AansltnrGeguitwlngArbdnst" type="str:AansluitnummerGegevensuitwisseling" minOccurs="0"/>
							<xsd:element name="RdnGnGgvnsuitw" type="str:RedenGeenGegevensuitwisseling" minOccurs="0"/>
							<xsd:element name="IDWrkgvrVerzekeraar" type="str:IdentificatieWerkgever" minOccurs="0"/>
							<xsd:element name="IdWrkgvrUWV" type="str:IdentificatieWerkgever" minOccurs="0"/>
							<xsd:element name="Lhnr" type="str:Loonheffingnummer" minOccurs="0"/>
							<xsd:element name="IdVrzkrWGACd" type="str:IdentificatieVerzekeraarCode" minOccurs="0"/>
							<xsd:element name="IdVrzkrERDZWCd" type="str:IdentificatieVerzekeraarCode" minOccurs="0"/>
							<xsd:element name="IdVrzkrCollectieveZorgCd" type="str:IdentificatieVerzekeraarCode" minOccurs="0"/>
							<xsd:element name="SectorVolgensSBI" type="str:SectorVolgensSbi" minOccurs="0"/>
							<xsd:element name="Personeelssterkte" minOccurs="0" maxOccurs="999">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="PeildatPersoneelssterkte" type="xsd:date"/>
										<xsd:element name="VorigePeildatPersoneelssterkte" type="xsd:date" minOccurs="0"/>
										<xsd:element name="AantWrknmrs" type="str:Aantal7"/>
										<xsd:element name="AantWrknmrsInDienstSindsVorigePeildat" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantWrknmrsUitDienstSindsVorigePeildat" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantalNulurencntrcten" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantFTE" type="str:Aantal7" minOccurs="0"/>
										<xsd:element name="AantVrouwelijkeWrknmrs" type="str:Aantal5" minOccurs="0"/>
										<xsd:element name="AantVrouwelijkeFTE" type="str:Aantal5" minOccurs="0"/>
										<xsd:element name="AantMannelijkeWrknmrs" type="str:Aantal5" minOccurs="0"/>
										<xsd:element name="AantMannelijkeFTE" type="str:Aantal5" minOccurs="0"/>
										<xsd:element name="AantUrenFTE" type="str:Aantal3" minOccurs="0"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="StrAdrNl" minOccurs="0" maxOccurs="9">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="SrtAdrsCd" minOccurs="0">
											<xsd:simpleType>
												<xsd:restriction base="xsd:string">
													<xsd:length value="2"/>
													<xsd:enumeration value="01"/>
													<xsd:enumeration value="02"/>
													<xsd:enumeration value="03"/>
													<xsd:enumeration value="05"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
										<xsd:element name="Ingdat" type="xsd:date" minOccurs="0"/>
										<xsd:element name="Enddat" type="xsd:date" minOccurs="0"/>
										<xsd:element name="Pc" type="str:PostcodeNederland"/>
										<xsd:element name="Wnpl" type="str:Plaatsnaam" minOccurs="0"/>
										<xsd:element name="StraatLang" type="str:StraatnaamLang" minOccurs="0"/>
										<xsd:element name="Huisnr" type="str:Huisnummer"/>
										<xsd:element name="HuisToev" type="str:HuisnummerToevoeging" minOccurs="0"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="StrAdrBl" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="SrtAdrsCd" minOccurs="0">
											<xsd:simpleType>
												<xsd:restriction base="xsd:string">
													<xsd:length value="2"/>
													<xsd:enumeration value="01"/>
													<xsd:enumeration value="02"/>
													<xsd:enumeration value="03"/>
													<xsd:enumeration value="05"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
										<xsd:element name="Ingdat" type="xsd:date" minOccurs="0"/>
										<xsd:element name="Enddat" type="xsd:date" minOccurs="0"/>
										<xsd:element name="LocomsBtl" type="str:Locatieomschrijving" minOccurs="0"/>
										<xsd:element name="PcBtl" type="str:PostcodeBuitenland" minOccurs="0"/>
										<xsd:element name="WnplBtl" type="str:Plaatsnaam"/>
										<xsd:element name="RegBtl" type="str:RegionaamBuitenland" minOccurs="0"/>
										<xsd:element name="LandCd" type="str:IsoLandcode"/>
										<xsd:element name="Landnm" type="str:Landnaam" minOccurs="0"/>
										<xsd:element name="StraatLang" type="str:StraatnaamLang" minOccurs="0"/>
										<xsd:element name="HuisnrBtl" type="str:HuisnummerBuitenland"/>
										<xsd:element name="HuisnrToevBtl" type="str:HuisnummerToevoegingBuitenland" minOccurs="0"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="AdministratieveEenheid" minOccurs="0">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="NmIp" type="str:SignificantDeelVanDeAchternaam"/>
										<xsd:element name="LhNr" type="str:Loonbelastingnummer" minOccurs="0"/>
										<xsd:element name="SectorRisicogroep" minOccurs="0">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="CdSectorOsv" type="str:CodeSectorOsv"/>
													<xsd:element name="CdRisicopremiegroep" type="str:CodeRisicopremiegroep" minOccurs="0"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="OrgEenh" minOccurs="0" maxOccurs="999">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="VrwrkCd" type="str:Verwerkingscode"/>
										<xsd:element name="IngdatMut" type="xsd:date" minOccurs="0"/>
										<xsd:element name="NmOrgeenh" type="str:NaamOrganisatie"/>
										<xsd:element name="OrgeenhCd" type="str:OrganisatieEenheid"/>
										<xsd:element name="OndOrgeenhCd" type="str:OrganisatieEenheid"/>
										<xsd:element name="Personeelssterkte" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="PeildatPersoneelssterkte" type="xsd:date"/>
													<xsd:element name="VorigePeildatPersoneelssterkte" type="xsd:date" minOccurs="0"/>
													<xsd:element name="AantWrknmrs" type="str:Aantal7"/>
													<xsd:element name="AantWrknmrsInDienstSindsVorigePeildat" type="str:Aantal7" minOccurs="0"/>
													<xsd:element name="AantWrknmrsUitDienstSindsVorigePeildat" type="str:Aantal7" minOccurs="0"/>
													<xsd:element name="AantalNulurencntrcten" type="str:Aantal7" minOccurs="0"/>
													<xsd:element name="AantFTE" type="str:Aantal7" minOccurs="0"/>
													<xsd:element name="AantVrouwelijkeWrknmrs" type="str:Aantal5" minOccurs="0"/>
													<xsd:element name="AantVrouwelijkeFTE" type="str:Aantal5" minOccurs="0"/>
													<xsd:element name="AantMannelijkeWrknmrs" type="str:Aantal5" minOccurs="0"/>
													<xsd:element name="AantMannelijkeFTE" type="str:Aantal5" minOccurs="0"/>
													<xsd:element name="AantUrenFTE" type="str:Aantal3" minOccurs="0"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="ArboCntrct" minOccurs="0" maxOccurs="9">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="VrwrkCd" type="str:Verwerkingscode"/>
										<xsd:element name="Cntrnr" type="str:IdentificatieContract"/>
										<xsd:element name="Ingdat" type="xsd:date"/>
										<xsd:element name="IngdatMut" type="xsd:date" minOccurs="0"/>
										<xsd:element name="Enddat" type="xsd:date" minOccurs="0"/>
										<xsd:element name="StatusCntrctCd" type="str:StatusContract"/>
										<xsd:element name="TypArbContCod" type="str:TypeArbocontract"/>
										<xsd:element name="Intermediair" minOccurs="0">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="HndlsnmOrg" type="str:HandelsnaamOrganisatie"/>
													<xsd:element name="Com" minOccurs="0" maxOccurs="9">
														<xsd:complexType>
															<xsd:sequence>
																<xsd:element name="SrtComCd">
																	<xsd:simpleType>
																		<xsd:restriction base="xsd:string">
																			<xsd:length value="2"/>
																			<xsd:enumeration value="06"/>
																			<xsd:enumeration value="08"/>
																			<xsd:enumeration value="10"/>
																		</xsd:restriction>
																	</xsd:simpleType>
																</xsd:element>
																<xsd:element name="NrCom" type="str:NummerAdresCommunicatie"/>
															</xsd:sequence>
														</xsd:complexType>
													</xsd:element>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
										<xsd:element name="Dnstvrlnng" minOccurs="0" maxOccurs="9">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="VrwrkCd" type="str:Verwerkingscode"/>
													<xsd:element name="DnstvrlnngId" type="str:IdentificatieDienstverlening"/>
													<xsd:element name="TypeArbopakketCd" type="str:TypeArbopakket" minOccurs="0"/>
													<xsd:element name="TypeArbopakketOms" type="str:Omschrijving70" minOccurs="0"/>
													<xsd:element name="RdnEindDnstvrl" type="str:RedenEindeDienstverlening" minOccurs="0"/>
													<xsd:element name="Ingdat" type="xsd:date"/>
													<xsd:element name="IngdatMut" type="xsd:date" minOccurs="0"/>
													<xsd:element name="Enddat" type="xsd:date" minOccurs="0"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Verzekering" minOccurs="0" maxOccurs="99">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="VrwrkCd" type="str:Verwerkingscode"/>
										<xsd:element name="Cntrnr" type="str:IdentificatieContract" minOccurs="0"/>
										<xsd:element name="CntrnrPakket" type="str:IdentificatieContract" minOccurs="0"/>
										<xsd:element name="Ingdat" type="xsd:date" minOccurs="0"/>
										<xsd:element name="IngdatMut" type="xsd:date" minOccurs="0"/>
										<xsd:element name="Enddat" type="xsd:date" minOccurs="0"/>
										<xsd:element name="CntrctPerCd" type="str:ContractperiodeCode" minOccurs="0"/>
										<xsd:element name="StatusCntrctCd" type="str:StatusContract"/>
										<xsd:element name="RdnBeeindCntrct" type="str:RedenBeIndigingContract" minOccurs="0"/>
										<xsd:element name="SrtVerzekeringCd" type="str:SoortVerzekeringCode"/>
										<xsd:element name="WachttijdInDgn" type="str:Aantal3" minOccurs="0"/>
										<xsd:element name="LoonsrtCd" type="str:Loonsoort" minOccurs="0"/>
										<xsd:element name="MaxJrLoonVrzkrd" type="str:Bedrag92" minOccurs="0"/>
										<xsd:element name="PrcDkkngJr1" type="str:Percentage" minOccurs="0"/>
										<xsd:element name="PrcDkkngJr2" type="str:Percentage" minOccurs="0"/>
										<xsd:element name="PercWrkgvrslasten" type="str:Percentage" minOccurs="0"/>
										<xsd:element name="Productkenmerk" type="str:ProductkenmerkVerzuimverzekering" minOccurs="0"/>
										<xsd:element name="InloopJN">
											<xsd:simpleType>
												<xsd:restriction base="xsd:string">
													<xsd:length value="1"/>
													<xsd:pattern value="\D*"/>
													<xsd:enumeration value="J"/>
													<xsd:enumeration value="N"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
										<xsd:element name="UitloopJN">
											<xsd:simpleType>
												<xsd:restriction base="xsd:string">
													<xsd:length value="1"/>
													<xsd:pattern value="\D*"/>
													<xsd:enumeration value="J"/>
													<xsd:enumeration value="N"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="MchtVrzm" minOccurs="0">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="VrwrkCd">
											<xsd:simpleType>
												<xsd:restriction base="xsd:string">
													<xsd:length value="2"/>
													<xsd:enumeration value="01"/>
													<xsd:enumeration value="02"/>
													<xsd:enumeration value="04"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
										<xsd:element name="Ingdat" type="xsd:date"/>
										<xsd:element name="Enddat" type="xsd:date" minOccurs="0"/>
										<xsd:element name="KpplCd" type="str:AansluitnummerGegevensuitwisseling"/>
										<xsd:element name="RdnEndMCd" type="str:RedenEindeMachtigingCode" minOccurs="0"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Com" minOccurs="0" maxOccurs="9">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="SrtComCd">
											<xsd:simpleType>
												<xsd:restriction base="xsd:string">
													<xsd:length value="2"/>
													<xsd:enumeration value="01"/>
													<xsd:enumeration value="02"/>
													<xsd:enumeration value="04"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
										<xsd:element name="NrCom" type="str:NummerAdresCommunicatie"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Cntprsn" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="Persnr" type="str:Sleutelwaarde35" minOccurs="0"/>
										<xsd:element name="Achternaam" type="str:Achternaam"/>
										<xsd:element name="Voorl" type="str:Voorletters"/>
										<xsd:element name="Roepnaam" type="str:Roepnaam" minOccurs="0"/>
										<xsd:element name="GslchtCd" type="str:Geslacht"/>
										<xsd:element name="RolCntprsnCd" minOccurs="0">
											<xsd:simpleType>
												<xsd:restriction base="xsd:string">
													<xsd:length value="2"/>
													<xsd:enumeration value="02"/>
													<xsd:enumeration value="03"/>
													<xsd:enumeration value="05"/>
												</xsd:restriction>
											</xsd:simpleType>
										</xsd:element>
										<xsd:element name="Com" minOccurs="0" maxOccurs="unbounded">
											<xsd:complexType>
												<xsd:sequence>
													<xsd:element name="SrtComCd">
														<xsd:simpleType>
															<xsd:restriction base="xsd:string">
																<xsd:length value="2"/>
																<xsd:enumeration value="06"/>
																<xsd:enumeration value="08"/>
																<xsd:enumeration value="10"/>
															</xsd:restriction>
														</xsd:simpleType>
													</xsd:element>
													<xsd:element name="NrCom" type="str:NummerAdresCommunicatie"/>
												</xsd:sequence>
											</xsd:complexType>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:simpleType name="AansluitnummerGegevensuitwisseling">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="70"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Aantal3">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:totalDigits value="3"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Aantal5">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:totalDigits value="5"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Aantal7">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:totalDigits value="7"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Achternaam">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="200"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Bedrag92">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="9"/>
			<xsd:fractionDigits value="2"/>
			<xsd:pattern value="[\-+]?[0-9]{1,7}[.][0-9]{2}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Berichtreferentienummer">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="512"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CodeArbodienst">
		<xsd:restriction base="xsd:string">
			<xsd:length value="3"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CodeRisicopremiegroep">
		<xsd:restriction base="xsd:string">
			<xsd:length value="2"/>
			<xsd:pattern value="\d*"/>
			<xsd:enumeration value="00"/>
			<xsd:enumeration value="01"/>
			<xsd:enumeration value="02"/>
			<xsd:enumeration value="03"/>
			<xsd:enumeration value="04"/>
			<xsd:enumeration value="05"/>
			<xsd:enumeration value="06"/>
			<xsd:enumeration value="07"/>
			<xsd:enumeration value="08"/>
			<xsd:enumeration value="09"/>
			<xsd:enumeration value="10"/>
			<xsd:enumeration value="11"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CodeSectorOsv">
		<xsd:restriction base="xsd:string">
			<xsd:length value="3"/>
			<xsd:pattern value="\d*"/>
			<xsd:enumeration value="001"/>
			<xsd:enumeration value="002"/>
			<xsd:enumeration value="003"/>
			<xsd:enumeration value="004"/>
			<xsd:enumeration value="005"/>
			<xsd:enumeration value="006"/>
			<xsd:enumeration value="007"/>
			<xsd:enumeration value="008"/>
			<xsd:enumeration value="009"/>
			<xsd:enumeration value="010"/>
			<xsd:enumeration value="011"/>
			<xsd:enumeration value="012"/>
			<xsd:enumeration value="013"/>
			<xsd:enumeration value="014"/>
			<xsd:enumeration value="015"/>
			<xsd:enumeration value="016"/>
			<xsd:enumeration value="017"/>
			<xsd:enumeration value="018"/>
			<xsd:enumeration value="019"/>
			<xsd:enumeration value="020"/>
			<xsd:enumeration value="021"/>
			<xsd:enumeration value="022"/>
			<xsd:enumeration value="023"/>
			<xsd:enumeration value="024"/>
			<xsd:enumeration value="025"/>
			<xsd:enumeration value="026"/>
			<xsd:enumeration value="027"/>
			<xsd:enumeration value="028"/>
			<xsd:enumeration value="029"/>
			<xsd:enumeration value="030"/>
			<xsd:enumeration value="031"/>
			<xsd:enumeration value="032"/>
			<xsd:enumeration value="033"/>
			<xsd:enumeration value="034"/>
			<xsd:enumeration value="035"/>
			<xsd:enumeration value="038"/>
			<xsd:enumeration value="039"/>
			<xsd:enumeration value="040"/>
			<xsd:enumeration value="041"/>
			<xsd:enumeration value="042"/>
			<xsd:enumeration value="043"/>
			<xsd:enumeration value="044"/>
			<xsd:enumeration value="045"/>
			<xsd:enumeration value="046"/>
			<xsd:enumeration value="047"/>
			<xsd:enumeration value="048"/>
			<xsd:enumeration value="049"/>
			<xsd:enumeration value="050"/>
			<xsd:enumeration value="051"/>
			<xsd:enumeration value="052"/>
			<xsd:enumeration value="053"/>
			<xsd:enumeration value="054"/>
			<xsd:enumeration value="055"/>
			<xsd:enumeration value="056"/>
			<xsd:enumeration value="057"/>
			<xsd:enumeration value="058"/>
			<xsd:enumeration value="059"/>
			<xsd:enumeration value="060"/>
			<xsd:enumeration value="061"/>
			<xsd:enumeration value="062"/>
			<xsd:enumeration value="063"/>
			<xsd:enumeration value="064"/>
			<xsd:enumeration value="065"/>
			<xsd:enumeration value="066"/>
			<xsd:enumeration value="067"/>
			<xsd:enumeration value="068"/>
			<xsd:enumeration value="069"/>
			<xsd:enumeration value="998"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ContractperiodeCode">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="2"/>
			<xsd:enumeration value="01"/>
			<xsd:enumeration value="02"/>
			<xsd:enumeration value="03"/>
			<xsd:enumeration value="04"/>
			<xsd:enumeration value="05"/>
			<xsd:enumeration value="06"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Geslacht">
		<xsd:restriction base="xsd:string">
			<xsd:length value="1"/>
			<xsd:enumeration value="M"/>
			<xsd:enumeration value="O"/>
			<xsd:enumeration value="V"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="HandelsnaamOrganisatie">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Huisnummer">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:totalDigits value="5"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="HuisnummerBuitenland">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="9"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="HuisnummerToevoeging">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="HuisnummerToevoegingBuitenland">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="70"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="IdentificatieContract">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="40"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="IdentificatieDienstverlening">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="40"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="IdentificatieInzender">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="40"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="IdentificatieOntvanger">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="40"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="IdentificatieVerzekeraarCode">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="IdentificatieWerkgever">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="40"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="IsoLandcode">
		<xsd:restriction base="xsd:string">
			<xsd:length value="2"/>
			<xsd:pattern value="\D*"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Landnaam">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="40"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Locatieomschrijving">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="35"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Loonbelastingnummer">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="12"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Loonheffingnummer">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="12"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Loonsoort">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="2"/>
			<xsd:enumeration value="01"/>
			<xsd:enumeration value="02"/>
			<xsd:enumeration value="03"/>
			<xsd:enumeration value="04"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="NaamOrganisatie">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="70"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Nummer">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:totalDigits value="8"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="NummerAdresCommunicatie">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="512"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Omschrijving70">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="70"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="OrganisatieEenheid">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
			<xsd:maxLength value="70"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Percentage">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="6"/>
			<xsd:fractionDigits value="2"/>
			<xsd:minInclusive value="0"/>
			<xsd:pattern value="[0-9]{1,4}[.][0-9]{2}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Plaatsnaam">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="24"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="PostcodeBuitenland">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="9"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="PostcodeNederland">
		<xsd:restriction base="xsd:string">
			<xsd:length value="6"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ProductkenmerkVerzuimverzekering">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="70"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RedenBeIndigingContract">
		<xsd:restriction base="xsd:string">
			<xsd:length value="2"/>
			<xsd:enumeration value="01"/>
			<xsd:enumeration value="02"/>
			<xsd:enumeration value="03"/>
			<xsd:enumeration value="04"/>
			<xsd:enumeration value="05"/>
			<xsd:enumeration value="06"/>
			<xsd:enumeration value="07"/>
			<xsd:enumeration value="08"/>
			<xsd:enumeration value="99"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RedenEindeDienstverlening">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="2"/>
			<xsd:enumeration value="01"/>
			<xsd:enumeration value="02"/>
			<xsd:enumeration value="03"/>
			<xsd:enumeration value="04"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RedenEindeMachtigingCode">
		<xsd:restriction base="xsd:string">
			<xsd:length value="2"/>
			<xsd:enumeration value="01"/>
			<xsd:enumeration value="02"/>
			<xsd:enumeration value="03"/>
			<xsd:enumeration value="04"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RedenGeenGegevensuitwisseling">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="2"/>
			<xsd:enumeration value="01"/>
			<xsd:enumeration value="02"/>
			<xsd:enumeration value="03"/>
			<xsd:enumeration value="04"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RegionaamBuitenland">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="24"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Roepnaam">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="35"/>
			<xsd:pattern value="\D*"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="SectorVolgensSbi">
		<xsd:restriction base="xsd:integer">
			<xsd:totalDigits value="5"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="SignificantDeelVanDeAchternaam">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="200"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Sleutelwaarde35">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="35"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="SoortVerzekeringCode">
		<xsd:restriction base="xsd:string">
			<xsd:length value="2"/>
			<xsd:enumeration value="01"/>
			<xsd:enumeration value="02"/>
			<xsd:enumeration value="03"/>
			<xsd:enumeration value="04"/>
			<xsd:enumeration value="05"/>
			<xsd:enumeration value="06"/>
			<xsd:enumeration value="07"/>
			<xsd:enumeration value="08"/>
			<xsd:enumeration value="09"/>
			<xsd:enumeration value="10"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="StatusContract">
		<xsd:restriction base="xsd:string">
			<xsd:length value="2"/>
			<xsd:enumeration value="01"/>
			<xsd:enumeration value="02"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="StraatnaamLang">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="80"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Tekst35">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="35"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypeArbocontract">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="2"/>
			<xsd:enumeration value="01"/>
			<xsd:enumeration value="02"/>
			<xsd:enumeration value="03"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TypeArbopakket">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="70"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Verwerkingscode">
		<xsd:restriction base="xsd:string">
			<xsd:length value="2"/>
			<xsd:enumeration value="01"/>
			<xsd:enumeration value="02"/>
			<xsd:enumeration value="03"/>
			<xsd:enumeration value="04"/>
			<xsd:enumeration value="05"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="VestigingsnummerHandelsregister">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:totalDigits value="12"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="Voorletters">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="6"/>
			<xsd:pattern value="\D*"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>
